# Configuration file for Hugo Site
# Author : Manikandaraj Srinivasan
# Reference : https://gohugo.io/configuration/all/

baseURL = 'https://www.manikandaraj.com/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Manikandaraj Srinivasan'
titleCaseStyle = 'ap'

# Which theme to use
theme = 'mango'

#Whether to disable injection of a <meta name="generator"> tag into the home page. Default is false
disableHugoGeneratorInject = true

#Whether to allow emoji in Markdown
enableEmoji = true

#Whether to enable generation of a robots.txt file
enableRobotsTXT = true

#Menu Configuration for Header
[menus]
    [[menus.main]]
        name = 'Home'
        identifier = 'home'
        url = '/'
        weight = 10
    [[menus.main]]
        name = 'About'
        identifier = 'about'
        url = '/about/index.html'
        weight = 20
    [[menus.main]]
        name = 'Contact'
        identifier = 'contact'
        url = '/contact/index.html'
        weight = 30
    [[menus.main]]
        name = 'Blog'
        identifier = 'blog'
        url = '/blog/index.html'
        weight = 40
    [[menus.main]]
        name = 'My Resume'
        identifier = 'resume/'
        url = '/resume/index.html'
        weight = 50
    [[menus.main]]
        name = 'Referrals'
        identifier = 'referrals'
        url = '/referrals/index.html'
        weight = 60
    [[menus.main]]
        name = 'My Projects'
        identifier = 'projects'
        url = '/projects/index.html'
        weight = 70

[params]
    #For referring in Blog Posts, Copyright Message
    author.name = "Manikandaraj Srinivasan"
    author.email = "matrix@manikandaraj.com"

    #For SEO
    keywords = ["Mani", "Manikandaraj","Srinivasan", "blog", "techonlogy" , "Machine Learning", "Artificial Intelligence", "Python", "Java", "C++", "Linux"]
    description = "My Tech Blog - Manikandaraj Srinivasan!"

    dateFormatToUse = "Jan 02, 2006"

    [params.social]
        email = "mailto:matrix@manikandaraj.com"
        github = "https://github.com/manikandaraj/"
        linkedin = "https://www.linkedin.com/in/manikandaraj/"
        twitter = "https://x.com/manikandaraj"
        stack-overflow = "https://stackoverflow.com/users/1430572/manikandaraj-srinivasan"
        gitlab = "https://gitlab.com/Manikandaraj"
        goodreads = "http://localhost:1313"
        youtube = "http://localhost:1313"
        google = "http://localhost:1313"
        facebook = "http://localhost:1313"
        instagram = "http://localhost:1313"

#Whether to print template execution improvement hints to the console
templateMetrics = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

